### ISSUE TITLE
Confused with documentation and running the app

### ISSUE THREAD

**Issue by maraujop** [weluse/django-nose-selenium#3]
Hi there,

I was trying `django-nose-selenium` to see if the app fits my needs. First thing that is not clear to me since the beginning is what additional features I get using the app, why sould I code my Selenium tests using this app. I'm not criticizing the app or the effort behind it, just saying this point should be stressed much more.

I can't get it to run. I'm guessing one of the requirements is having `python-nose` installed. Do I need to put `noseselenium` within my `INSTALLED_APPS`. 

When I run `nosetests --with-selenium` I get this warnings:

<pre>
/usr/lib/pymodules/python2.6/nose/plugins/manager.py:369: RuntimeWarning: Unable to load plugin selenium = noseselenium.plugins:SeleniumPlugin: Settings cannot be imported, because environment variable DJANGO_SETTINGS_MODULE is undefined.
  RuntimeWarning)
/usr/lib/pymodules/python2.6/nose/plugins/manager.py:369: RuntimeWarning: Unable to load plugin djangoliveserver = noseselenium.plugins:DjangoLiveServerPlugin: Settings cannot be imported, because environment variable DJANGO_SETTINGS_MODULE is undefined.
  RuntimeWarning)
/usr/lib/pymodules/python2.6/nose/plugins/manager.py:369: RuntimeWarning: Unable to load plugin cherrypyliveserver = noseselenium.plugins:CherryPyLiveServerPlugin: Settings cannot be imported, because environment variable DJANGO_SETTINGS_MODULE is undefined.
  RuntimeWarning)
/usr/lib/pymodules/python2.6/nose/plugins/manager.py:369: RuntimeWarning: Unable to load plugin selenium_fixtures = noseselenium.plugins:SeleniumFixturesPlugin: Settings cannot be imported, because environment variable DJANGO_SETTINGS_MODULE is undefined.
  RuntimeWarning)
</pre>

Do I need to run the command in a specific location. I have a tests folder full of different .py files that have different Django basic unit tests. 

Thanks, best regards
Miguel Araujo

**Comment by passy** [comment]
Hey Miguel,

sorry for the long delay. The problem you described is indeed a documentation bug. Instead of directly running nosetests you have to pass the --with-selenium parameter to the django management command "test", which requires you to have django-nose installed and configured. I tried to cover that in the readme.

If you encounter another problem with running the tests, feel free to comment on this issue again.

Cheers,
Pascal

**Comment by maraujop** [comment]
Thanks Pascal,

I will try it when I have time, I desisted from using this app as I couldn't get it to work.

Cheers,
Miguel
