### ISSUE TITLE
Does not Run with Django 1.2

### ISSUE THREAD

**Issue by issackelly** [weluse/django-nose-selenium#7]
Because in plugins you require django.contrib.staticfiles

**Comment by passy** [comment]
That should be easy to fix. Thank you for your report.

**Comment by issackelly** [comment]
Thank you for your software! Made my job easier yesterday

Issac Kelly

On Aug 3, 2011, at 4:32 AM, passy
reply@reply.github.com
wrote:

**Comment by passy** [comment]
Glad to hear that. :)

I'm going to publish a new version on PyPI later this day.
