### ISSUE TITLE
livserver never loading the fixture data

### ISSUE THREAD

**Issue by chris-hireiq** [weluse/django-nose-selenium#8]
We've got django-nose-selenium so close to working properly.

Really, everything works except for the loading of the test sqlite data for use by CherryPy.  We determined that the default :memory: database was no good, so we're forcing sqlite to use a file.

However, it doesn't appear that the selenium_fixtures data gets loaded properly.  Actually, we can get the test data to load and be visible to the actual selenium webdriver script, but the process running CherryPy can't seem to see that data when we go to perform operations against it.

Besides the selenium_fixtures configuration, is there anything else we need to do to get this working?

**Comment by chris-hireiq** [comment]
We worked around this issue, but it would be great if the documentation and plugin assisted with these problems.
1. SQLITE had an issue with using the default :memory: database for testing.  CherryPy can't use that same database populated by the fixture populating mechanism.  You need to set the TEST_NAME for the test database to an actual file in your settings.py.
2. Additionally, you MUST use the Django TransactionTestCase as the base class for your Selenium test cases or else the initial fixture data is never persisted.  Once you do that, there doesn't seem to be a point to using the selenium_fixtures parameter vs the regular fixtures one (although I didn't experiment too much to determine the differences).

**Comment by cpbotha** [comment]
Thank you thank you thank you! I've been fighting for hours first with django-nose-selenium, then with django-sane-testing and now with django-nose-selinum again. Your tip on setting TEST_NAME to a real sqlite3 filename got everything working, in my case with a selenium_fixture. I did NOT need to use the TransactionTestCase.

Thanks again,
Charl

P.S. I'll be writing a full blog post documenting how to set this beast up. It's cost far too much time.

**Comment by cpbotha** [comment]
For future reference, here's that blog post: http://blog.timescapers.com/2011/08/27/django-nose-selenium-a-concise-tutorial/

**Comment by passy** [comment]
Awesome! I'm going to add a link to the README.

Thanks a lot!
