### ISSUE TITLE
selenium.py version

### ISSUE THREAD

**Issue by akoumjian** [weluse/django-nose-selenium#9]
Just had a couple of questions regarding the selenium.py file. 

Which version is this running? 
Why did you opt to embed this version instead of pulling it as a requirement for pip/easy_install?

**Comment by passy** [comment]
To be honest, I can't really remember why I chose to embed a version instead of requiring one. I think I needed to apply a custom patch to work around a specific edge case.

For the WebDriver-enabled version this will change, however, and I will list selenium as a requirement.
